//class Alpha extends Exception {
//  Alpha(String s){
//     super(String s);
//  }
//}
//
//public class own {
//    public static void main(String[] args) {
//        int a =10;
//        try {
//            int j = a/2;
//           if(j==5){
//               throw new Alpha("i am not going to handled ");
//           }
//        }catch (ArithmeticException ae){
//            System.out.println("handled" );
//        } catch (Alpha e) {
//            throw new RuntimeException(e);
//        }
//
//    }
//}
